services:
  - type: web
    name: encryption-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && pip3 install numpy pillow pycryptodome
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
